In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [3]:
Training_Set_X=np.array([[300.0,99.0,6.8],[308.0,103.0,8.36],[329.0,110.0,9.15],[332.0,118.0,9.36]])
X_test=np.array([[296.0,95.0,7.54],[293.0,97.0,7.8],[325.0, 112.0,8.96]])
Training_Set_Y=np.array([0.36,0.7,0.84,0.9])
Y_test=np.array([0.44,0.64,0.8])


print("Training_Set_X : ",Training_Set_X)
print("Training_Set_Y : ",Training_Set_Y)
print("X_test : ",X_test)
print("Y_test : ",Y_test)

#2.	Initialize the parameters with some random values.
np.random.seed(42)
weights1 = np.random.rand(3,3)
weights2=np.random.rand(3,)
bias1 = np.random.rand(1)
bias2 = np.random.rand(1)
#learning rate
lr = np.random.rand()
print("lr: ",lr,"\n")
print("weights1:",weights1,"\n")
print("weights2:",weights2,"\n")


Training_Set_X :  [[300.    99.     6.8 ]
 [308.   103.     8.36]
 [329.   110.     9.15]
 [332.   118.     9.36]]
Training_Set_Y :  [0.36 0.7  0.84 0.9 ]
X_test :  [[296.    95.     7.54]
 [293.    97.     7.8 ]
 [325.   112.     8.96]]
Y_test :  [0.44 0.64 0.8 ]
lr:  0.18182496720710062 

weights1: [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]] 

weights2: [0.70807258 0.02058449 0.96990985] 



In [4]:
# SE to save all Squared Errors values
SE=list()

#3.Perform a feed-forward stage to propagate the input forward through the network. 
for epoch in range(len(Training_Set_X)):
    print("At Epoch: ",epoch)
 # feedforward step1 
    R = Training_Set_X[epoch].dot( weights1.T) + bias1 # linear response
    #feedforward step2 
    H = sigmoid(R)  # activation f’n
    S=H.dot( weights2.T)+bias2  # linear response
    # backpropagation step 1 
    Yhat=sigmoid(S)
    error = (Yhat) - Training_Set_Y[epoch]
    SE.append((error**2))

#5.	Print the content of the input/output of hidden layers and output layer at the feed forward stages.
  #input of hidden layers
    print("R :",R)
    #the output of hidden layers
    print("H1 ,H2,& H3 :" ,H)
   #input of output layer
    print("S :",S)
    #the output of output layer
    print("Yhat :",Yhat)
    print("Error :",error)
    
    #4.Preform the back-propagation algorithm using sum square error (SSE).
    # backpropagation step 2
    S_Si_der = sigmoid_der(S)
    G2= (error * S_Si_der)*(H)
    R_Si_der=sigmoid_der(R)
   # Update weights2    
   #6.Print the content of the weight matrices after each epoch (4 epochs)
    for i in range(len(weights2)):
        weights2[i] -= (lr * G2[i])
    print("The content of the weight2 matrices  :\n",weights2,"\n")
        # Update weights1   
    for i in range(len(weights1)):        
        for j in range(len(weights1[i])):
            weights1[i][j] -= (error * S_Si_der*weights2[i]*R_Si_der[i]*Training_Set_X[epoch][j])
           
    print("The content of the weight1 matrices  :\n",weights1,"\n")
#sum square error 
print("SSE:",sum(SE))

At Epoch:  0
R : [212.29275343 196.93659604 108.0965468 ]
H1 ,H2,& H3 : [1. 1. 1.]
S : [1.91090603]
Yhat : [0.8711209]
Error : [0.5111209]
The content of the weight2 matrices  :
 [0.69763888 0.0101508  0.95947616] 

The content of the weight1 matrices  :
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]] 

At Epoch:  1
R : [220.23384216 202.59328993 112.9636597 ]
H1 ,H2,& H3 : [1. 1. 1.]
S : [1.87960495]
Yhat : [0.86756574]
Error : [0.16756574]
The content of the weight2 matrices  :
 [0.69413829 0.00665021 0.95597557] 

The content of the weight1 matrices  :
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]] 

At Epoch:  2
R : [235.33246001 216.38048425 120.72152944]
H1 ,H2,& H3 : [1. 1. 1.]
S : [1.86910318]
Yhat : [0.86635447]
Error : [0.02635447]
The content of the weight2 matrices  :
 [0.69358346 0.00609538 0.95542074] 

The content of the weight1 matrices  :
 [[0.37

In [5]:
#7.	Test and report the result of classifying the testing examples.
# SE2 to save all Squared Errors values
SE2=list()
for epoch in range(len(X_test)):
    # feedforward step1 
    R = X_test[epoch].dot( weights1.T) + bias1 # linear response
    #feedforward step2 
    H = sigmoid(R)  # activation f’n
    S=H.dot( weights2.T)+bias2  # linear response
    # backpropagation step 1 
    Yhat=sigmoid(S)
    error = (Yhat) - Y_test[epoch]
    SE2.append((error**2))
#5.	Print the content of the input/output of hidden layers and output layer at the feed forward stages.
    print("Example  :",epoch+1)
    print("The predicted chance of acceptance :",Yhat)
    print("Error :",error)
#sum square error 
print("SSE:",sum(SE2))


Example  : 1
The predicted chance of acceptance : [0.86640949]
Error : [0.42640949]
Example  : 2
The predicted chance of acceptance : [0.86640949]
Error : [0.22640949]
Example  : 3
The predicted chance of acceptance : [0.86640949]
Error : [0.06640949]
SSE: [0.23749653]
